# Generated by Django 5.2.8 on 2025-11-08 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='título')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('channel', models.CharField(choices=[('ALERT', 'Alerta'), ('EMAIL', 'Email')], default='ALERT', max_length=10, verbose_name='canal')),
                ('is_read', models.BooleanField(default=False, verbose_name='já lida')),
                ('related_model', models.CharField(blank=True, max_length=100, verbose_name='modelo referenciado')),
                ('object_id', models.CharField(blank=True, max_length=36, verbose_name='ID do objeto')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
