# Generated by Django 5.2.8 on 2025-11-07 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nome da sala')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='código interno')),
                ('location', models.CharField(max_length=255, verbose_name='localização')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='capacidade')),
                ('description', models.TextField(blank=True, verbose_name='observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=60, verbose_name='identificador/hostname')),
                ('processador', models.CharField(max_length=120, verbose_name='processador')),
                ('memoria', models.PositiveIntegerField(verbose_name='memória (GB)')),
                ('tipo_memoria', models.CharField(choices=[('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5'), ('LPDDR4', 'LPDDR4'), ('OUTRO', 'Outro')], default='DDR4', max_length=20, verbose_name='tipo da memória')),
                ('armazenamento', models.CharField(max_length=120, verbose_name='armazenamento')),
                ('placa_mae', models.CharField(max_length=120, verbose_name='placa mãe')),
                ('numero_serie', models.CharField(max_length=100, unique=True, verbose_name='número de série')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponível')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='rooms.room', verbose_name='sala')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
                'ordering': ['room', 'hostname', 'numero_serie'],
            },
        ),
    ]
