# Generated by Django 5.2.8 on 2025-11-07 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data da reserva')),
                ('start_time', models.TimeField(verbose_name='hora de início')),
                ('end_time', models.TimeField(verbose_name='hora de término')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Agendada'), ('CANCELLED', 'Cancelada')], default='SCHEDULED', max_length=15, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelada em')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='professor')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='rooms.room', verbose_name='sala')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-date', '-start_time'],
                'constraints': [models.UniqueConstraint(fields=('room', 'date', 'start_time', 'end_time'), name='unique_room_exact_slot', violation_error_message='Já existe uma reserva exata para este horário.')],
            },
        ),
    ]
