# Generated by Django 5.2.8 on 2025-11-07 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome do software')),
                ('version', models.CharField(blank=True, max_length=60, verbose_name='versão')),
                ('description', models.TextField(blank=True, verbose_name='detalhes adicionais')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovada'), ('INSTALLED', 'Instalado'), ('REJECTED', 'Rejeitado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=15, verbose_name='status')),
                ('admin_notes', models.TextField(blank=True, verbose_name='anotações administrativas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='solicitada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='software_requests', to='rooms.machine', verbose_name='máquina')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_requests', to='reservations.reservation', verbose_name='reserva')),
            ],
            options={
                'verbose_name': 'Solicitação de Software',
                'verbose_name_plural': 'Solicitações de Software',
                'ordering': ['-created_at'],
            },
        ),
    ]
