# Generated by Django 5.2.8 on 2025-11-07 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Criado'), ('UPDATED', 'Atualizado'), ('DELETED', 'Removido'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CANCELLED', 'Cancelado')], max_length=20, verbose_name='ação')),
                ('model', models.CharField(max_length=100, verbose_name='modelo afetado')),
                ('object_id', models.CharField(blank=True, max_length=36, verbose_name='ID do objeto')),
                ('description', models.TextField(verbose_name='descrição detalhada')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registrado em')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-created_at'],
            },
        ),
    ]
